@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.2.0/C4_Container.puml

'ref http://plantuml.com/stdlib
!include <office/Users/user.puml>
!include <office/Users/mobile_user.puml>

title MASH data import - proof of concept

Person(practitioners, Practitioner)


System_Boundary(googles, "Google") {
    System_Ext(gform, "Google Form", "filled in by practitioners")
    System_Ext(gscript, "Google Script", "triggered by new row on Google Sheet")
    System_Ext(gsheet, "Google Sheet", "form submission data")
    System_Ext(gdoc, "Google Doc",  "document", "")

}


System_Boundary(system, "Social Care") {
Container(aws_s3, "AWS S3", "object storage service")
Container(aws_SQS, "AWS SQS", "message queuing service", "Creates a message queue")
Container(aws_lambda, "AWS Lambda",  "Lambda", "")
Container(social_care_service_api,  "Social Care Case Viewer API", "Lambda, C#", "Provides service API capabilities to the Social Care System.") 
Container(service_api_api_gateway, "SC API Gateway",  "API Gateway", "Provides routing and auth via API keys.")
ContainerDb(service_api_rds, "Social Care DB", "PostgreSQL/MongoDB", "Data storage")
}

 Rel(practitioners, gform, "Fill in a referral", "")
 Rel(gform, gsheet, "Form submission", "Google automation")
 Rel(gsheet, gscript, "Form submission", "Google automation")
 Rel(gscript, gsheet, "Update row with unique ID", "Google automation")
 Rel(gscript, service_api_api_gateway, "Send form data and unique ID ")
 Rel(service_api_api_gateway, aws_s3, "Forward data")
 Rel(aws_s3, aws_SQS, "Forward data")
 Rel(aws_SQS, aws_lambda, "Forward data")
 Rel(aws_lambda, gdoc, "Generate Google Doc using form data in message")
 Rel(aws_lambda, gsheet, "Update sheet with Google Doc edit URL")
 Rel(aws_lambda, social_care_service_api, "Send form data, unique ID and Google Doc URL")
 Rel(social_care_service_api,service_api_rds , "Send data to")

SHOW_DYNAMIC_LEGEND()
@enduml