@startuml

'ref http://plantuml.com/stdlib
!include <c4/C4_Context.puml>
!include <office/Users/user.puml>
!include ./c4_shared.puml
'!include https://raw.githubusercontent.com/LBHackney-IT/cv-19-res-support-v3/add-c4-diagrams/docs/diagrams/c4_shared.puml

LAYOUT_AS_SKETCH()

title Social Care System Context Diagram

Person(care_practitioners, Social Care Practitioner, "<$user> <$user>\n Adult and Children" )
Person_Ext(data_insights_team, Data and Insights Team, "<$user>" )

System_Boundary(system, "Social Care") {

  System(social_care_application, "Social Care Application", "Allows practitioners to view case information.")
  System_Ext(google_auth, "Google Groups", "Provides User Authentication and Authorisation")
  System_Ext(google_forms, "Google Forms", "Temporary data submissions (partial?)")
  System_Ext(qlik, "Qlik Analytics", "Case progress reporting")
}

Rel(care_practitioners, social_care_application, "Views data and navigates cases using")
Rel(social_care_application, google_auth, "Authenticates practitioners via")
Rel(google_forms, social_care_application, "Periodic data import")
Rel(care_practitioners, google_forms, "Redirected to add data with")
Rel(data_insights_team, qlik, "View case statistics with")

SHOW_DYNAMIC_LEGEND()

@enduml
