@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.2.0/C4_Container.puml

'ref http://plantuml.com/stdlib
!include <office/Users/user.puml>
!include <office/Users/mobile_user.puml>
' !include https://raw.githubusercontent.com/LBHackney-IT/cv-19-res-support-v3/development/docs/diagrams/c4_shared.puml

title Social Care System Container Diagram

Person(care_practitioners, Social Care Practitioner, "<$user> <$user>\n Adult and Children" )
Person(data_insight_team, Data and Insight Team )

System_Ext(qlik, "Qlik Analytics", "ETL & Case progress reporting")

System_Boundary(googles, "Google") {
  System_Ext(google_auth, "Google Groups", "Provides User Authentication and Authorisation")
  System_Ext(google_forms, "Google Forms", "Data submissions (57 forms)")
  System_Ext(google_sheets, "Google Sheets", "Form submission data")
  System_Ext(google_docs, "Google Docs", "Generated for viewing (AppScript)")
}

System_Boundary(system, "Social Care") {
  Container(social_care_front_end, "Social Care Front End", "Lambda, Next.js (React)", "Allows practitioners to edit case information.")
  Container(social_care_service_api, "Social Care Case Viewer Service API", "Lambda, C#", "Provides backend API for the Social Care Front End")
  Container(mosaic_platform_api, "Mosaic Resident Information Platform API",  "Lambda, C#", "Provides person search")
  Container(mosaic_historic_data_api, "Residents Social Care Platform API",  "Lambda, C#", "Provides historic case and visit data")
  
  Container(adult_social_care_front_end, "Adult Social Care Packages Front End", "Lambda, React", "Allows adult social care workers to build and manage care packages.")
  Container(adult_social_care_api, "Adult Social Care Packages API", "Lambda, .NET (C#)", "Allows adult social care workers to build and manage care packages.")
  Container(adult_social_care_transactions_api, "Adult Social Care Package Transactions API", "Lambda, .NET (C#)", "Manages transactions and payments relating to adult social care.")
}

Rel(care_practitioners, social_care_front_end, "Manage cases using", "JSON/HTTPS")
Rel(care_practitioners, google_forms, "Redirected by Social Care App to add data in", "JSON/HTTPS")
Rel(care_practitioners, google_docs, "Redirected by Social Care App to view form submissions", "HTTPS")
Rel(care_practitioners, qlik, "View / create dashboards and reports")

Rel(adult_social_care_front_end, adult_social_care_api, "Manage care packages using", "JSON/HTTPS")
Rel(adult_social_care_api, adult_social_care_transactions_api, "Manage transactions / payments using", "JSON/HTTPS")

Rel_D(data_insight_team, qlik, "Manage data extraction and reporting pipelines")

Rel(social_care_front_end, social_care_service_api, "Read / Write", "JSON/HTTPS")
Rel(social_care_front_end, google_auth, "Authenticates practitioners via", "JSON/HTTPS")

Rel(social_care_service_api, mosaic_historic_data_api, "Retrieves from", "JSON/HTTPS")
Rel(social_care_service_api, mosaic_platform_api, "Retrieves from", "JSON/HTTPS")

Rel(qlik, social_care_service_api, "Hourly CSV export of form data to S3", "Qlik / AWS integration")

Rel(google_forms, google_sheets, "Submitted data stored in")
Rel(google_sheets, qlik, "Data ingestion", "Google API")
Rel(google_sheets, google_docs, "Generated from form data")
Rel_U(google_docs, google_auth, "Access restricted with")

SHOW_DYNAMIC_LEGEND()
@enduml
